language: c
env:
  global:
    # Ubuntu version
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C flags
    - C_FLAGS="-Wall -pedantic -Werror -Wextra -Wstrict -Wwrite-strings -fno-common -g -O3 -std=gnu11"
    # Misc
    - COVERAGE=false


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
       apt:
         packages: &precise_latest_boost_packages
           - gcc-6
           - cmake
	   - cmake-date
         sources:
           - ubuntu-toolchain-r-test
      	   - george-edison55-precise-backports # cmake


before_install:
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export C_FLAGS=${C_FLAGS}" "${ENV_C_FLAGS}


install:
    - echo ${PATH}

script:
  - mkdir -p build
  - cd build
  - cmake --build .
  # tests
  - cd ../tests/external
  - bash test_sender_empfaenger.sh
after_success:
  # coverity
  - cd $TRAVIS_BUILD_DIR
  - if ([ "$CC" == "gcc" ] && [ "$TRAVIS_BRANCH" == "coverity_scan" ]); then
      curl -s "https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh" | bash || true;
    fi
