language: c
sudo: required

os:
    - linux
    - osx
compiler:
  - gcc
  - gcc-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # gcc
    packages:
      - gcc-7
      - make

before_install:
      - uname -a
      - gcc -v

script:
  - make all
  # tests
  - cd tests/external
  - bash test_sender_empfaenger.sh
  - cd ../..
  - make clean freeshm
