language: c
compiler:
  - gcc
  - gcc-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # gcc
      - george-edison55-precise-backports # cmake
    packages:
      - gcc-7
      - make


env:
  global:
    # Ubuntu version
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C flags
    - C_FLAGS="-Wall -pedantic -Werror -Wextra -Wstrict -Wwrite-strings -fno-common -g -O3 -std=gnu11"
    # Misc
    - COVERAGE=false


before_install:
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export C_FLAGS=${C_FLAGS}" "${ENV_C_FLAGS}


install:
    - echo ${PATH}

script:
  - make all
  # tests
  - cd /tests/external
  - bash test_sender_empfaenger.sh
  - make clean
after_success:
  # coverity
  - cd $TRAVIS_BUILD_DIR
  - if ([ "$CC" == "gcc" ] && [ "$TRAVIS_BRANCH" == "coverity_scan" ]); then
      curl -s "https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh" | bash || true;
    fi
